### PR TITLE
Add Metrics and Target Exploration

### PR DESCRIPTION
**Pull request by trey-ivy**
This is a big PR, and I do apologize.  I can work on breaking it up if you prefer.  

Basically I've tried to extend the datamodel in /ent/schema to be more representative of what comes in from the BES message w/regards to metrics, targets and tests.  For a good visual representation of what the new schema looks like I've also add entviz which generates a graphical representation of the schema at `ent/gen/ent/schema-viz.html`.  

Then I updated summary.go and save.go to persist the model data to the database.  I'm grouping this data w/the bazel invocation object, which makes the most sense to me on where to put it.

After that I built out a few components to display the data.  I used and added the recharts package for this purpose.  I also built some tables that are searchable, sortable and filterable and have some color coding where it makes sense.  

Obviously this still needs a lot of work, but its a start.

Runners Tab:
image

Action Cache Tab:
image

Actions Data Tab:
image

Artifacts Tab: (plans to extend this and include navigable artifacts for the build)
image

Memory Metrics Tab:
image

Timing Tab: (maybe rename to other and include network tab here)
image

Targets Tab:
image

Tests Tab:
image

System Network Metrics (optionally displayed if available)
image

### CODE REVIEW

**Comment by EdSchouten** [comment]
Awesome work. @trey-ivy! Please work together with @mortenmj to get this merged. The two of you now own this repo. ;-)

**Comment by mortenmj** [comment]
@trey-ivy I tried rebasing this on https://github.com/buildbarn/bb-portal/pull/3 and had a couple of test failures. Would you mind if we merged that PR first, so to get some basic CI up and running?

**Comment by trey-ivy** [comment]
no that sounds like a good plan to me

**Comment by mortenmj** [comment]
@trey-ivy could you clean up the git history?

**Comment by gempesaw** [comment]
@trey-ivy all the new statistics are really cool! thank you for contributing this PR

i have been seeing a segfault in some code that came from this PR, stacktrace below

(but .. it may also be due to my own set up? on some invocations that succeed, it says 90% of my action cache hits failed due to `corrupted cache` or something, so .. i'm thinking i may want to clear my CAS/AC, as i'm just using toy data anyway for now)

```
2024/10/03 15:28:17 INFO Stream started event="context.Background.WithValue(type transport.connectionKey, val <not Stringer>).WithValue(type peer.peerKey, val <not Stringer>).WithCancel.WithValue(type metadata.mdIncomingKey, val <not Stringer>).WithValue(type grpc.serverKey, val <not Stringer>).WithValue(type grpc.streamKey, val <not Stringer>).WithValue(type grpc.rpcInfoContextKey, val <not Stringer>)"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0xe0293f]

goroutine 33 [running]:
github.com/buildbarn/bb-portal/pkg/summary.readActionCacheStatistics(...)
	/go/src/app/pkg/summary/summarizer.go:606
github.com/buildbarn/bb-portal/pkg/summary.readActionSummary(0xc0007bd880)
	/go/src/app/pkg/summary/summarizer.go:587 +0x5f
github.com/buildbarn/bb-portal/pkg/summary.Summarizer.handleBuildMetrics({0xc0001c6e08, {{0xc0003788a0, 0x2, 0x2}, {0xc0003788e0, 0x2, 0x2}}}, 0xc0008eb560)
	/go/src/app/pkg/summary/summarizer.go:416 +0x66
github.com/buildbarn/bb-portal/pkg/summary.Summarizer.ProcessEvent({0xc0001c6e08, {{0xc0003788a0, 0x2, 0x2}, {0xc0003788e0, 0x2, 0x2}}}, 0xc000378c00)
	/go/src/app/pkg/summary/summarizer.go:114 +0x54e
github.com/buildbarn/bb-portal/internal/api/grpc/bes.processBazelEvent({0x25534e8, 0xc0007bb9e0}, 0xc0007c2280, 0xc0007c2100)
	/go/src/app/internal/api/grpc/bes/bes.go:115 +0x290
github.com/buildbarn/bb-portal/internal/api/grpc/bes.BES.PublishBuildToolEventStream({0xc0001ff1e0?, {0xc0006739b0?}}, {0x255ad38, 0xc0004c5ec0})
	/go/src/app/internal/api/grpc/bes/bes.go:73 +0x245
google.golang.org/genproto/googleapis/devtools/build/v1._PublishBuildEvent_PublishBuildToolEventStream_Handler({0x1eee440?, 0xc000708b80}, {0x2558638, 0xc0007ae1e0})
	/go/pkg/mod/google.golang.org/genproto@v0.0.0-20240227224415-6ceb2ff114de/googleapis/devtools/build/v1/publish_build_event.pb.go:817 +0xd8
google.golang.org/grpc.(*Server).processStreamingRPC(0xc000381400, {0x25534e8, 0xc0007bb8f0}, {0x255b900, 0xc0002be600}, 0xc00020f0e0, 0xc000673e60, 0x36483a0, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1663 +0x1208
google.golang.org/grpc.(*Server).handleStream(0xc000381400, {0x255b900, 0xc0002be600}, 0xc00020f0e0)
	/go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1784 +0xe3a
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	/go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1019 +0x8b
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 113
	/go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1030 +0x125
```

**Comment by trey-ivy** [comment]
@gempesaw hey Dan, I just saw this comment.  If you could please create an issue and provide as much detail as possible I'll try to take a look.  seems like we probably just need to add some null checking somewhere.

**Pull request merged**
